/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Job = IDL.Record({
  'leftSerial' : IDL.Nat,
  'prefix' : IDL.Text,
  'rightSerial' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Text], ['query']),
  'setSettings' : IDL.Func([IDL.Text], [], []),
  'submitJob' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Job = IDL.Record({
    'leftSerial' : IDL.Nat,
    'prefix' : IDL.Text,
    'rightSerial' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Text], ['query']),
    'setSettings' : IDL.Func([IDL.Text], [], []),
    'submitJob' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };